### PR TITLE
1.105.2

### LINKED ISSUE #24: Wrong indenting on prometheus server resources
In `cost-analyzer/charts/prometheus/templates/server-deployment.yaml:135` there are indents introduced before the line `{{ toYaml .Values.server.resources | indent 12 }}`. This causes Helm to complain `error converting YAML to JSON`. As a result we cannot update our Kubecost version.

### PR DESCRIPTION
**Pull request by jessegoodier**
Update kubecost to 1.105.2
resolves #24  fix resources indentation on Prometheus server
allow global securityContexts in cost-analyzer and prometheus pods

### CODE REVIEW

**Comment by chipzoller** [comment]
We need to implement the same CI checks in [cost-analyzer-helm-chart](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/.github/workflows/chart.yaml) here.

**Comment by chipzoller** [comment]
You could add this as part of the PR that way the checks are triggered with these changes.

**Comment by jessegoodier** [comment]
> We need to implement the same CI checks in [cost-analyzer-helm-chart](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/.github/workflows/chart.yaml) here.

We are likely deprecating this chart in 1.107. One more update after this for 1.106.

Is it worth the effort? If it is, do you mind adding it?

**Comment by chipzoller** [comment]
I think longer term we need to bring this back into the main Helm chart once sub-charts have been removed so we maintain only a single chart.

**Comment by thomasvn** [comment]
Before approval, could we get this tested with `helm template`? Specifically making sure that the template renders the config described in https://github.com/kubecost/openshift-helm-chart/issues/24

```yaml
prometheus:
  server:
    resources:
```

**Comment by chipzoller** [comment]
Here is the template result with release name `foo`

```yaml
# Source: cost-analyzer/charts/prometheus/templates/server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: "server"
    app: prometheus
    release: foo
    chart: prometheus-11.0.2
    heritage: Helm
  name: foo-prometheus-server
  namespace: default
spec:
  selector:
    matchLabels:
      component: "server"
      app: prometheus
      release: foo
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: "server"
        app: prometheus
        release: foo
        chart: prometheus-11.0.2
        heritage: Helm
    spec:
      serviceAccountName: foo-prometheus-server
      containers:
        - name: prometheus-server-configmap-reload
          image: "jimmidyson/configmap-reload:v0.7.1"
          imagePullPolicy: "IfNotPresent"
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://127.0.0.1:9090/-/reload
          resources:
            {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true

        - name: prometheus-server
          image: "quay.io/prometheus/prometheus:v2.35.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --storage.tsdb.retention.time=15d
            - --config.file=/etc/config/prometheus.yml
            - --storage.tsdb.path=/data
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle
            - --query.max-concurrency=1
            - --query.max-samples=1e+08
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          resources:
            {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: storage-volume
              mountPath: /data
              subPath: ""
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 300
      volumes:
        - name: config-volume
          configMap:
            name: foo-prometheus-server
        - name: storage-volume
          persistentVolumeClaim:
            claimName: foo-prometheus-server
```

**Comment by thomasvn** [comment]
@chipzoller Thank you!! If possible, could you do it one more time with the following to be sure

```yaml
prometheus:
  server:
    resources:
      requests:
        cpu: "10m"
        memory: "55Mi"
```

**Comment by chipzoller** [comment]
Confirmed it does work.

**Review by thomasvn — APPROVED** [review]

**Comment by chipzoller** [comment]
Do any of the README instructions need to change? In looking them over, it doesn't look like they reference this values file.

**Pull request merged**
